#!/bin/bash
#
#Vanuse skript
#
read -p "Palun sisesta siia oma vanus: " #kysib vanust
if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "Sa oled laps!"
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "Sa oled nooruk!"
elif test $vanus -ge 18 -a $vanus -lt 30
then
	echo "Sa oled täiskasvanu!"
elif test $vanus -ge 63
then
	echo "Sa oled seenior!"
else
	echo "vigane sisend!"
fi
