#!/bin/bash
#
#see skript tuvastab kas sisestatud arv on paarisarv
#
echo -n "Palun sisestage siia täisarv: " #küsib arvu
read arv
jaak=$(( $arv % 2 ))
if [ $jaak -eq 0 ]
then
	echo "$arv on paaris"
else
	echo "$arv on paaritu"
fi
#
#skripti lõpp
