#!/bin/bash
#
osch=0
echo "1. Unix (Son OS)"
echo "2. Linux (Red hat)"


echo -n "select your os choice [1 or 2]"
read osch

if [ $osch -eq 1 ] ; then
	echo "you pick up unix (Sun OS)
else ### nested if i.e if whitin if ########
	if [ osch -eq 2 ] ; then
		echo "you pick up linux (Red Hat)"
	else
		echo "what you don't like about Unix/linux"
		fi
	fi
#
#
