#!/bin/bash
#
#Kuupäev
echo -n "Today is " #ilma reavahetuseta
date +"%A, %B %d, %Y" #näitab päeva, kuud, aastat
ecgo -n "time is " #ilma reavahetuseta
date +"%T" #näitab kellaaega
echo #tühi rida
echo -n "Calendar of " #tekst ilma reavahetuseta
cal #näitab kalendrit
#
#skripti lõpp
