#!/bin/bash
#
#arvutab kolmnurga hypoteesi
#
#
echo "palun sisesta kolmnurga kylgede pikkused: (cm)"
read a b
a1='expr $a \* $a'
b1='expr $a1 \* $b'
d='expr $a1 \+ $b1'
c=(echo "$d" | awk `{print sqrt($1)}')
echo "hypotenuus on: $c"
#
#l6pp
